//! Every backend should stamp the kuva version into its output for later issue triage.

use kuva::prelude::*;

fn sample_plot() -> (Vec<Plot>, Layout) {
    let plots: Vec<Plot> = vec![ScatterPlot::new()
        .with_data(vec![(1.0_f64, 2.0), (3.0, 4.0), (5.0, 1.0)])
        .into()];
    let layout = Layout::auto_from_plots(&plots).with_title("stamp test");
    (plots, layout)
}

#[test]
fn svg_carries_version_stamp() {
    let (plots, layout) = sample_plot();
    let svg = kuva::render_to_svg(plots, layout);
    // Must still open with the <svg> tag (many tests rely on this prefix).
    assert!(svg.starts_with("<svg"), "SVG must start with <svg");
    let stamp = format!("Generated by kuva {}", kuva::VERSION);
    assert!(
        svg.contains(&stamp),
        "SVG should embed the version stamp: {stamp}"
    );
}

#[cfg(feature = "png")]
#[test]
fn png_carries_version_stamp() {
    let (plots, layout) = sample_plot();
    let png = kuva::render_to_png(plots, layout, 1.0).expect("png render");
    // The PNG `Software` tEXt chunk stores "Software\0kuva <version>" as latin-1 bytes.
    let needle = format!("kuva {}", kuva::VERSION);
    let hay = String::from_utf8_lossy(&png);
    assert!(
        hay.contains("Software") && hay.contains(&needle),
        "PNG should contain a Software text chunk with the kuva version"
    );
}

#[cfg(feature = "pdf")]
#[test]
fn pdf_renders_with_metadata() {
    let (plots, layout) = sample_plot();
    let pdf = kuva::render_to_pdf(plots, layout).expect("pdf render");
    assert!(pdf.starts_with(b"%PDF"), "should be a PDF");
    assert!(pdf.len() > 200, "PDF should be non-trivial");
}
